config/routes.rb
Rails.application.routes.draw do
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index', as: :home

  resources :groups, :countries, :devices, :roles, :games, :users, :videos, :banners
  resources :faqs, except: :show
  resources :abouts, except: :show
  resources :find_teams, except: :show
  resources :find_users, except: :show
  resources :sponsors, only: %i[new create]
  resources :contacts, only: %i[new create]
  resources :group_invitations, only: %i[index show destroy]

  get 'administrator/index'
  post '/mensaje_global', to: 'administrator#mensaje_global', as: :mensaje_global
  # get '/sponsors', to: 'home#sponsors'
  get '/ggwp', to: 'home#ggwp'
  get '/terms_conditions', to: 'home#terms_conditions'
  put '/video/:id/vote', to: 'videos#vote', as: 'vote'
  put '/home/:id/firsttime', to: 'home#firsttimeuser', as: 'firsttimeuser'
  get 'contacts/new'
  get 'sponsors/new'
  get '/sponsors', to: 'sponsors#new'
  get '/list_equipos', to: 'home#list_user_equipos'
  get '/ggwp_all', to: 'home#ggwp_all'
  put '/group_invitations', to: 'group_invitations#new_invitation', as: 'new_invitation'

  resources :users do
    get :description
    get :avatar
    get :authorization
  end

  resources :groups do
    get :avatar
    get :new_member
    post :new_member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :group_invitations, dependent: :destroy
  has_many :find_users, dependent: :destroy

  validates :name, uniqueness: true
  validate :acceptable_image

  before_save :check_league

  def acceptable_image
    return unless image.attached?

    unless image.byte_size <= 1.megabyte
      errors.add(:image, "El archivo no debe exceder 1MB")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]

    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "La imagen debe ser .jpg, .jpeg o .png")
    end
  end

  def check_league
    if self.league.nil? || self.league.empty?
      self.league = 'Sin liga'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  belongs_to :role, optional: true
  has_many :videos, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :group_invitations, dependent: :destroy
  has_many :find_users, dependent: :destroy
  has_many :find_teams, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :nickname, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :whatsapp, presence: true, numericality: { only_integer: true }, on: :create
  validate :acceptable_image
  before_create :check_age, :check_tipo
  before_save { self.email = email.downcase }
  before_save :assign_role, :check_firsttime
  before_save { self.trophy = 0 if trophy.nil? }

  def assign_role
    self.role = Role.find_by name: 'jugador' if role.nil?
  end

  def check_firsttime
    self.firsttime = 1 if firsttime.nil?
  end

  def check_tipo
    self.tipo = 'amateur'
  end

  def check_age
    user_age = ((Time.zone.now - self.borndate.to_time) / 1.year.seconds).floor
    if user_age < 18
      self.menor = true
    else
      self.active = true
    end
  end

  def acceptable_image
    return unless image.attached?

    unless image.byte_size <= 1.megabyte
      errors.add(:image, "El archivo no debe exceder 1MB")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]

    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "La imagen debe ser .jpg, .jpeg o .png")
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb
  before_action :set_selection_list, only: [:new, :edit, :create, :update]
  layout('application')

  # GET /groups
  def index
    @country_options = Country.all.map {|country| [country.name, country.id]}
    @game_options = Game.all.map { |game| [game.name, game.id] }.sort
    @breadcrumbs_subtitle = 'Listado de Equipos'
    @league_options = Group.all.collect { |group| group.league }.uniq

    if params[:nombre].nil?
      groups = Group.all

      if params[:filter].present?
        find_teams_all = Group.all
        params_select = params.select {|k,v| [k.to_sym,v] if v.present? && k != 'controller' && k != 'filter' && k != 'action' && k != 'commit'}
        search_params = params_select.to_enum.each {|param| ["#{param.first} LIKE ?", param.last]}

        groups = find_teams_all.where(search_params.permit!)
      end
    else
      find_groups = Group.where(Group.arel_table[:name].matches('%'+params[:nombre]+'%'))
      groups = Group.where(id: find_groups.ids)
    end
=begin
    if params[:filter].present?
      case params[:filter]
      when "pais"
        @groups = Group.where(country: params[:country])
      when "juego"
        @groups = Group.all.filter do |group|
          if group.games.present? && group.games.scan(/\d*\d/).include?(params[:game])
            group
          end
        end
      when "liga"
        @groups = Group.where(league: params[:liga]).sort
      end
    else
      @groups = Group.all
    end
=end

    if params[:user].present?
      groups = Group.where(user_id: params[:user])
      @breadcrumbs_subtitle = 'Mis Equipos'
    end

    @groups_pagination = groups.paginate(page: params[:page], per_page: 24)
  end

  # GET /groups/1
  def show
    @group_games = @group.games.scan(/\d*\d/) unless @group.games.nil?
    @group_players = @group.players.scan(/\d*\d/) unless @group.players.nil?

    if params[:remove_player].present?
      @user = User.find_by(id: params[:remove_player])
      @user_teams = @user.teams.scan(/\d*\d/).delete(@group.id)
      @user.teams = @user_teams
      @user.save
      @group_players = @group.players.scan(/\d*\d/)
      @group_players.delete(@user.id.to_s)
      @group.players = @group_players
      @group.save
      redirect_to group_path(@group), notice: "Jugador expulsado"
    end
  end

  # GET /groups/new
  def new
    @breadcrumbs_subtitle = 'Nuevo'
    @user = User.find_by id: params[:user]

    if @user.option == 'equipo'
      @group = Group.new
    else
      redirect_to user_path(current_user.id), notice: 'No puedes crear otro grupo'
    end

  end

  # GET /groups/1/edit
  def edit
    redirect_to user_path(current_user.id), notice: 'No estas autorizado para hacer esto' unless @group.user_id == current_user.id || current_user.role.id == 2
    @group_games = @group.games.scan(/\d*\d/) unless @group.games.nil?
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    @user = User.find_by(id: current_user.id)

    if @group.save
      if @user.groups.nil?
        @user.groups = [params[@group.id]]
      else
        #@user_groups = @user.groups.scan(/\d*\d/)
        @user_groups = @user.groups.ids
        #@user.groups = @user_groups << params[@group.id]
      end
      @user.save!
      redirect_to @group, notice: 'El grupo fué creado.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    @group.image.purge

    if @group.update(group_params)
      redirect_to @group, notice: 'El grupo fué actualizado.'
    else
      unless params[:group][:image].present?
        render :edit
      end
      redirect_to avatar, notice: 'El archivo no debe exceder 1MB y debe ser una imagen'
    end
  end

  # DELETE /groups/1
  def destroy
    redirect_to user_path(current_user.id), notice: 'No estas autorizado para hacer esto' unless @group.user_id == current_user.id || current_user.role.id == 2
    @users = User.all
    @users.each do |user|
      @user_teams = user.teams.scan(/\d*\d/) - [params[:id]] unless user.teams.nil?
      user.teams = @user_teams
      user.save
    end
    @group.destroy
    if current_user.role.id == 2
      redirect_to groups_url, notice: 'El grupo fué eliminado.'
    else
      redirect_to user_path(current_user), notice: 'El grupo fué eliminado.'
    end
  end

  def avatar
    @breadcrumbs_subtitle = 'Cambiar avatar'
    @group = Group.find_by(id: params[:group_id])
  end

  def new_member
    @group = Group.find_by(id: params[:group_id])
    @breadcrumbs_subtitle = 'Nuevo miembro'
    @users = User.all.map { |user| [user.name, user.id] unless user.role_id == 2}.compact

    if params["/groups/find_user/new_member"].present? || params[:find_user].present?
      if params["/groups/find_user/new_member"].present?
        @find_user = params['/groups/find_user/new_member'][:user]
      else
        @find_user = params[:find_user]
      end
      @users = User.where("nickname like ?", "%" + @find_user + "%").where.not(role_id: 2)

      if params[:user_id].present?
        @user = User.find_by(id: params[:user_id])
        if @user.groups.nil?
          @user.groups = [@group.id.to_s]
          @user.save
          if @group.players.nil?
            @add_player_to_group = Group.find_by(id: @group.id)
            @add_player_to_group.players = [@user.id]
          else
            @add_player_to_group = Group.find_by(id: @group.id)
            @group_players = @group.players.scan(/\d*\d/)
            @add_player_to_group.players = @group_players << @user.id.to_s
          end
          @add_player_to_group.save
          redirect_to group_path(@group.id)
        else
          @user_groups = @user.groups.scan(/\d*\d/)
          if @user_groups.include?(@group.id.to_s)
            redirect_to group_new_member_path(@group.id), notice: "El jugador ya está incluido en el grupo"
          else
            @user.groups = @user_groups << @group.id.to_s unless @user_groups.include?(@group.id.to_s)
            @user.save
            if @group.players.nil?
              @add_player_to_group = Group.find_by(id: @group.id)
              @add_player_to_group.players = [@user.id]
            else
              @add_player_to_group = Group.find_by(id: @group.id)
              @group_players = @group.players.scan(/\d*\d/)
              @add_player_to_group.players = @group_players << @user.id.to_s
            end
            @add_player_to_group.save
            redirect_to group_path(@group.id)
          end
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to home_path, notice: 'El grupo que buscas no existe'
  end

  def set_selection_list
    @country_list = Country.all.map { |country| [country.name, country.id] }.sort
    @games_list = Game.all.map { |game| [game.name, game.id] }.sort
  end

  def set_breadcrumb
    @breadcrumbs = 'Equipos'
    @equipos_active = 'active'
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :country, :league, :user_id, :image, games: [], players: [])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: 'nk-form') do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row vertical-gap">
    <div class="offset-sm-3 col-lg-6">
      <div class="row vertical-gap">
        <div class="col-sm-12">
          <label for="name" class="col-form-label-sm">Nombre</label>
          <%= form.text_field :name, class: 'form-control' %>
        </div>


        <div class="col-sm-12">
          <%= form.label 'País', class: 'col-form-label-sm mt-15' %>
          <%= form.select :country, options_for_select(@country_list, @group.country), { include_blank: false }, class: 'form-control' %>
        </div>

        <div class="col-sm-12">
          <%= form.label 'Liga', class: 'col-form-label-sm mt-15' %>
          <%= form.text_field :league, class: 'form-control' %>
        </div>


        <div class="col-sm-12">
          <%= form.label 'Juegos', class: 'col-form-label-sm mt-15' %>
          <%= form.select :games, options_for_select(@games_list, @group_games), { include_hidden: false }, multiple: true, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <!--<div class="field">
          <%#= form.label :user_id %>
  <%#= form.text_field :user_id %>
        </div>-->

  <div class="col-12">
    <div class="text-center">
      <div class="nk-gap-1"></div>
      <%= form.submit 'Confirmar', class: 'nk-btn nk-btn-rounded nk-btn-color-white' do %>
        <span class="icon"><i class="ion-paper-airplane"></i></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/groups/avatar.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <!-- START: Reg-form -->
      <%= form_with(model: @group, class: 'nk-form') do |f| %>

        <div class="row vertical-gap mt-50">
          <div class="offset-0 offset-3 col-lg-6">
            <div class="row vertical-gap">
              <p class="mb-3 text-white">Recomendamos una imagen de 200x200px y fondo transparente</p>
              <%= f.file_field :image, class: 'form-control' %>
            </div>
            <div class="text-white">
              <i class="fa fa-times" id="file_size" style="color: red;"></i> El archivo no supera 1MB <br>
              <i class="fa fa-times" id="file_extension" style="color: red;"></i> El archivo es .jpeg, .jpg, .png
            </div>
            <img id="image_preview" class="img-fluid p-50">
          </div>
          <div class="col-12">
            <div class="text-center">
              <div class="nk-gap-1"></div>
              <%= f.submit 'Confirmar', class: 'nk-btn nk-btn-rounded nk-btn-color-white', id: 'confirm_button', disabled: true do %>
                <span class="icon"><i class="ion-paper-airplane"></i></span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- END: Reg-form -->
      <% end %>

      <div class="text-center">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

<script>
  $("#group_image").change(function(){
      var fileExtension = ['jpeg', 'jpg', 'png'];
      if ($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
          $("#file_extension").removeClass('fa-check').addClass('fa-times').css('color', 'red');
      } else {
          $("#file_extension").removeClass('fa-times').addClass('fa-check').css('color', 'green');
          const file = this.files[0];
          console.log(file);
          if (file) {
              let reader = new FileReader();
              reader.onload = function (event) {
                  console.log(event.target.result);
                  $('#image_preview').attr('src', event.target.result);
              }
              reader.readAsDataURL(file);
          }
      }
      if (this.files[0].size <= 1048576){
          $("#file_size").removeClass('fa-times').addClass('fa-check').css('color', 'green');
      } else {
          $("#file_size").removeClass('fa-check').addClass('fa-times').css('color', 'red');
      }
      if (($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) != -1) && (this.files[0].size <= 1048576)) {
          $("#confirm_button").enable()
      } else {
          $("#confirm_button").disable()
      }
  });
</script>

app/views/groups/edit.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <%= render 'form', group: @group %>

      <div class="text-center">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/groups/index.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">
      <% if user_signed_in? %>
        <div class="row filtros">
          <div class="col-md-6">
            <%= form_with(controller: controller, method: 'get', class: 'd-flex') do |f| %>
              <%= f.text_field :nombre, class: 'form-control', placeholder: 'Buscar equipo', data: { turbolinks: false } %>
              <%= button_tag type: 'submit', class: 'nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3 ml-15' do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-6 boton-filtro">
            <%= link_to 'Limpiar filtros', groups_path, class:"nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3 mr-5" %>
            <button class="nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3" data-toggle="modal" data-target="#modalFiltrarBusqueda">Filtrar Equipos</button>
          </div>
        </div>
      <% end %>

      <div class="row">
        <!-- START: Teams -->
        <% @groups_pagination.each do |group| %>
          <div class="col-xl-4 col-md-6  my-2">
            <div class="nk-team">
              <div class="row">
                <div class="col-sm-4 d-flex justify-content-center align-items-center">
                  <div class="nk-team-logo">
                    <% if group.image.present? %>
                      <%= image_tag(group.image, class: 'img-fluid') %>
                    <% else %>
                      <%= image_tag("logo.png", class: 'img-fluid') %>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-8">
                  <div class="nk-team-cont">
                    <div class="nk-content">
                      <h3 class="h5 mb-20">
                        <span class="text-main-1"><%= link_to group.name, group %></span>
                      </h3>
                      <p class="h5 mb-20 ml-30">
                        <% if user_signed_in? && group.user_id == current_user.id %>
                          <%= link_to edit_group_path(group) do %>
                            <i class="fa fa-edit"></i>
                          <% end %>
                          <%= link_to group, method: :delete, data: { confirm: 'Estás seguro?' } do %>
                            <i class="fa fa-trash ml-10"></i>
                          <% end %>
                        <% end %>
                      </p>
                    </div>
                    <i class="fa fa-user"></i> <%= group.players.nil? ? 'Todavia no tiene miembros' : group.players.scan(/\d*\d/).count %>
                    <!--<div class="nk-team-photo" style="background-image: url(<%#= image_path('team-photo.png') %>);"></div>-->
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <!-- END: Teams -->
      </div>
      <div class="nk-gap-2"></div>
      <!-- START: Pagination -->
      <div class="col-lg-9">
        <div class="nk-pagination nk-pagination-left">
          <nav>
            <%= will_paginate(
                  @groups_pagination,
                  previous_label: '<span class="ion-ios-arrow-back"></span>',
                  next_label: '<span class="ion-ios-arrow-forward"></span>',
                  )
            %>
          </nav>
        </div>
      </div>
      <!-- END: Pagination -->

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>
<div class="nk-gap-2"></div>

app/views/groups/new.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <%= render 'form', group: @group %>

      <div class="text-center">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/groups/new_member.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <% if params["/groups/find_user/new_member"].present? || params[:find_user] %>
        <div class="table-responsive">
          <table class="table table-sm text-white">
            <thead>
            <tr>
              <th scope="col">Nickname</th>
              <th scope="col">Opciones</th>
            </tr>
            </thead>
            <tbody>
            <% if @users.present? %>
              <% @users.each do |user| %>
                <% unless user.option == "equipo" %>
                  <tr>
                    <td><%= user.nickname %></td>

                    <td class="user-<%= user.id %>">
                      <%= link_to user, class: 'mx-3' do %>
                        <i class="fa fa-eye"></i>
                      <% end %>
                      <% unless GroupInvitation.where(user_id: user.id, group_id: @group.id).present? %>
                        <% if user.groups.nil? %>
                          <%#= link_to 'Invitar al equipo', group_new_member_path(find_user: @find_user, user_id: user.id), class:'nk-btn nk-btn-rounded nk-btn-color-white .nk-btn-color-dark-3 ml-3' %>
                          <%= button_to 'Invitar al equipo', group_invitations_path(user_id: user.id, group_id: @group.id, user_invited: 1), method: :put, class:'nk-btn nk-btn-rounded nk-btn-color-white .nk-btn-color-dark-3 ml-3', onclick:"removeButton(#{user.id});" %>
                        <% else %>
                          <% unless user.group_ids.include?(@group.id) %>
                            <%#= link_to 'Invitar al equipo', group_new_member_path(find_user: @find_user, user_id: user.id), class:'nk-btn nk-btn-rounded nk-btn-color-white .nk-btn-color-dark-3 ml-3' %>
                            <%= button_to 'Invitar al equipo', group_invitations_path(user_id: user.id, group_id: @group.id, user_invited: 1), method: :put, class:'nk-btn nk-btn-rounded nk-btn-color-white .nk-btn-color-dark-3 ml-3', onclick:"removeButton(#{user.id});" %>
                          <% end %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            <% else %>
              <tr>
                <td>La búsqueda no obtuvo resultados</td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <%= form_with scope: group_new_member_path(:find_user) , class: 'nk-form', local: true do |form| %>
          <div class="row vertical-gap">
            <div class="offset-sm-3 col-lg-6">
              <div class="row vertical-gap">
                <div class="col-sm-12">
                  <%= form.label 'Buscar usuario', class: 'col-form-label-sm mt-15' %>
                  <%= form.text_field :user, class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class="col-12">
              <div class="text-center">
                <div class="nk-gap-1"></div>
                <%= form.submit 'Buscar miembro', class: 'nk-btn nk-btn-rounded nk-btn-color-white' do %>
                  <span class="icon"><i class="ion-paper-airplane"></i></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="text-center mt-25">
        <% if params["/groups/find_user/new_member"].present? || params[:find_user] %>
          <%= link_to 'Volver', :back %>
        <% else %>
          <%= link_to 'Volver', group_path(@group.id) %>
        <% end %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

<script type="text/javascript" charset="utf-8">
  function removeButton(user_id) {
      $(".user-"+user_id+" .button_to").addClass('d-none');
  }
</script>

app/views/groups/show.html.erb
<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <!-- START: Teammate Card -->
      <div class="nk-teammate-card m-auto padding-teammate background-team" style=" background: url(<%= asset_path('pro_teams/sub_equipo_fondo.webp') %>);">
        <div class="row">
          <div class="col-lg-2 group-avatar">
            <% avatar = User.find_by(id: @group.user_id).image %>
            <% if @group.image.attached? %>
              <%= image_tag(@group.image, class: 'img-fluid') %>
            <% else %>
              <%= image_tag("logo.png", class: 'img-fluid') %>
            <% end %>
            <%# if @group.user_id == current_user.id %>
              <%#= link_to group_avatar_path(@group), class: 'boton-edicion avatar', data: { toggle: 'tooltip', placement: 'bottom', title: 'Editar' } do %>
                <!--<span class="fas fa-edit"></span>-->
              <%# end %>
            <%# end %>
          </div>
          <div class="col-lg-10">
            <div class="player-info">
              <h3><strong class="h3"><%= @group.name %></strong></h3>
              <p>
                <% if @group.league.present? %>
                  Liga: <strong class="h5"><%= @group.league %></strong><br>
                <% else %>
                  <%= link_to 'Necesitas cargar tu liga', group_path(@group) if current_user.id == @group.user_id %><br>
                <% end %>
                <% if @group.country.present? %>
                  País: <strong class="h5"><%= Country.find_by(id: @group.country).name %></strong> <br>
                <% else %>
                  <%= link_to 'Necesitas cargar tu país', group_path(@group) if current_user.id == @group.user_id %><br>
                <% end %>
                <% if @group_games.present? %>
                  Juegos:
                  <% @group_games.each do |game_id| %>
                    <% group_game = Game.find_by(id: game_id) %>
                    <strong class="h5"><%= group_game.name unless group_game.nil? %> </strong>
                  <% end %> <br>
                <% else %>
                  <%= link_to 'Necesitas cargar tus juegos', group_path(@group) if current_user.id == @group.user_id %><br>
                <% end %>
                Pertenece al Equipo: <%= link_to User.find_by(id: @group.user_id).nickname, user_path(@group.user_id) %>
              </p>
            </div>
          </div>
        </div>
        <% if @group.user_id == current_user.id %>
          <%= link_to edit_group_path(@group), class: 'boton-edicion', data: { toggle: 'tooltip', placement: 'bottom', title: 'Editar' } do %>
            <span class="fas fa-edit"></span>
          <% end %>
        <% end %>
      </div>

      <!-- END: Teammate Card -->

      <% if @group.user_id == current_user.id %>
        <div class="nk-gap-3"></div>
        <h3 class="nk-decorated-h-2">
          <span>Opciones</span>
        </h3>
        <div class="row">
          <div class="col-sm-4 mt-15 d-flex justify-content-between">
            <%= link_to 'crear búsqueda de jugadores', new_find_user_path, class: 'nk-btn nk-btn-rounded nk-btn-color-white nk-anchor' %>
            <%= link_to 'eliminar equipo', group_path(@group), method: :delete, data: { confirm: "Vas a eliminar el equipo #{@group.name}" }, class: 'nk-btn nk-btn-rounded btn-danger nk-anchor ml-md-5' %>
          </div>
        </div>
      <% end %>
      <div class="nk-gap-3"></div>
      <h3 class="nk-decorated-h-2">
        <span>Integrantes</span>
      </h3>
      <% if @group.user_id == current_user.id %>
        <div class="row">
          <div class="col-sm-4 mt-15">
            <%= link_to 'Nuevo miembro', group_new_member_path(group_id: @group.id), class: 'nk-btn nk-btn-rounded nk-btn-color-white nk-anchor' %>
          </div>
        </div>
      <% end %>
      <div class="mt-25">
        <% if @group.players.nil? || @group.players == "[]" %>
          "No hay miembros"
        <% else %>
          <div class="table-responsive">
            <table class="table table-sm text-white">
              <thead>
              <tr>
                <th scope="col">Nickname</th>
                <% if @group.user_id == current_user.id || @group_players.include?(current_user.id.to_s) %>
                  <th scope="col">Opciones</th>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <% @group_players.each do |player_id| %>
                <%
                  user = User.find_by(id: player_id)
                %>
                <tr>
                  <td>
                    <strong class="h5"><%= link_to user.name, user_path(player_id) if user.present? %></strong>
                  </td>
                  <% if @group.user_id == current_user.id || player_id.include?(current_user.id.to_s) %>
                    <td>
                      <%= link_to group_path(@group, remove_player: player_id), data: { toggle: 'tooltip', placement: 'bottom', title: 'Editar' } do %>
                        <span class="fas fa-trash"></span>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
              <% end %>
              </tbody>
            </table>
        <% end %>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="nk-gap-3"></div>