config/routes.rb
Rails.application.routes.draw do
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index', as: :home

  resources :groups, :countries, :devices, :roles, :games, :users, :videos, :banners
  resources :faqs, except: :show
  resources :abouts, except: :show
  resources :find_teams, except: :show
  resources :find_users, except: :show
  resources :sponsors, only: %i[new create]
  resources :contacts, only: %i[new create]
  resources :group_invitations, only: %i[index show destroy]

  get 'administrator/index'
  post '/mensaje_global', to: 'administrator#mensaje_global', as: :mensaje_global
  # get '/sponsors', to: 'home#sponsors'
  get '/ggwp', to: 'home#ggwp'
  get '/terms_conditions', to: 'home#terms_conditions'
  put '/video/:id/vote', to: 'videos#vote', as: 'vote'
  put '/home/:id/firsttime', to: 'home#firsttimeuser', as: 'firsttimeuser'
  get 'contacts/new'
  get 'sponsors/new'
  get '/sponsors', to: 'sponsors#new'
  get '/list_equipos', to: 'home#list_user_equipos'
  get '/ggwp_all', to: 'home#ggwp_all'
  put '/group_invitations', to: 'group_invitations#new_invitation', as: 'new_invitation'

  resources :users do
    get :description
    get :avatar
    get :authorization
  end

  resources :groups do
    get :avatar
    get :new_member
    post :new_member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  validates :video, uniqueness: true
  belongs_to :user
  has_many :votes, dependent: :destroy

  before_save :assign_not_approved

  def assign_not_approved
    self.approved = false if approved.nil?
  end

  def voted?(user)
    !!self.votes.find{ |vote| vote.user_id == user.id }
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy, :vote]
  before_action :set_breadcrumb
  layout('application')

  # GET /videos
  def index
    redirect_to ggwp_all_path
    @videos = Video.all
  end

  # GET /videos/1
  def show
    redirect_to ggwp_all_path, notice: 'No puedes realizar esta acción'
  end

  # GET /videos/new
  def new
    @video = Video.new
    @breadcrumbs_subtitle = 'Nuevo video'
  end

  # GET /videos/1/edit
  def edit
    redirect_to user_path(current_user.id), notice: 'No estas autorizado para hacer esto' unless @video.user_id == current_user.id || current_user.role.id == 2
    @breadcrumbs_subtitle = 'Editar video'
  end

  # POST /videos
  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id

    if @video.save
      @contact = Contact.new(
       nombre: current_user.nickname,
       email: current_user.email,
       nickname: '',
       usuario: 'info@freeagents.gg',
       asunto: 'Nuevo video',
       mensaje: 'Nuevo video pendiente de aprobación'
      )
      @contact.request = request
      @contact.deliver

      redirect_to user_path(current_user.id), notice: 'Nuevo video guardado.'
    else
      render :new
    end
  end

  # PATCH/PUT /videos/1
  def update
    if @video.update(video_params)
      redirect_to user_path(current_user.id), notice: 'Video modificado.'
    else
      render :edit
    end
  end

  # DELETE /videos/1
  def destroy
    redirect_to user_path(current_user.id), notice: 'No estas autorizado para hacer esto' unless @video.user_id == current_user.id || current_user.role.id == 2
    @video.destroy

    if params[:ggwp].present?
      redirect_to ggwp_path, notice: 'Video eliminado.'
    elsif params[:ggwp_all].present?
      redirect_to ggwp_all_path, notice: 'Video eliminado.'
    elsif params[:admin].present?
      redirect_to administrator_index_path(home: 'home')
    else
      redirect_to user_path(current_user.id), notice: 'Video eliminado.'
    end
  end

  def vote
    Vote.create(user_id: current_user.id, video_id: @video.id)
    @user = User.find_by(id: @video.user_id)
    if @user.trophy.nil?
      @user.trophy = 1
    else
      @user.trophy = @user.trophy.to_i + 1
    end
    @user.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def set_breadcrumb
      @breadcrumbs = 'compartir video'
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:video, :user_id, :approved, :embeded)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, class:'nk-form nk-form-style-1') do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    Ten en cuenta que todos los videos están sujetos a aprobación del Administrador del sitio.
    <br>
    Por el momento solo se admiten videos de youtube y twitch (no live)
    <br>
    Para agregar un video debes copiar la URL que figura en la barra de dirección de tu navegador.
  </p>
  <%= form.text_field :video, class: 'form-control', placeholder: 'Agregá la URL de tu video', id: 'video_url', required: true %>

  <%= form.text_field :embeded, id: 'embeded_video', class: 'd-none' %>

  <div id="preview_video" class="d-flex"></div>

  <div class="col-12">
    <div class="text-center">
      <div class="nk-gap-1"></div>
      <a href="" class="nk-btn nk-btn-rounded nk-btn-color-white" onclick="revisar(); return false;">Revisar</a>
      <%= form.submit 'Confirmar', id:'confirm_button', class: 'nk-btn nk-btn-rounded nk-btn-color-white', disabled: true do %>
        <span class="icon"><i class="ion-paper-airplane"></i></span>
      <% end %>
    </div>
  </div>

<% end %>

<script>
    function revisar(){
        event.preventDefault();
        let video = $("#video_url").val();
        let url = ""

        if (video.match(/youtube/gm)) {
            url = video.match(/(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/gm);
            result_url = url.toString().split("youtube.com/watch?v=").join("")
            video = '<iframe width="560" height="315" src="https://www.youtube.com/embed/' + result_url + '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
        }

        if (video.match(/twitch/gm)) {
            url = video.match(/(?:https:\/\/)?twitch\.tv\/(\S+)/gm);
            result_url = url.toString().split("twitch.tv/videos/").join("")
            console.log(result_url);
            video = '<iframe src="https://player.twitch.tv/?video=v' + result_url + '&parent=<%= request.host %>&parent=www.<%= request.host %>&autoplay=false" frameborder="0" allowfullscreen="true" scrolling="no" height="315" width="560"></iframe>'
            console.log(video);
        }

        if (url.length == 0) {
            $("#preview_video").html('<p>Hay un problema con tu video</p>')
        } else {
            $("#preview_video").html(video);
            $("#embeded_video").val(video);
            $("#confirm_button").removeAttr('disabled');
        }
    }
</script>

app/views/videos/edit.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="offset-0 offset-lg-3 col-lg-6">

      <%= render 'form', video: @video %>

      <div class="text-center pt-15">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>Votes</th>
      <th>Voted by</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.video %></td>
        <td><%= video.votes %></td>
        <td><%= video.voted_by %></td>
        <td><%= video.user_id %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="offset-0 offset-lg-3 col-lg-6">

      <%= render 'form', video: @video %>

      <div class="text-center pt-15">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= @video.video %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @video.votes %>
</p>

<p>
  <strong>Voted by:</strong>
  <%= @video.voted_by %>
</p>

<p>
  <strong>User:</strong>
  <%= @video.user_id %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>