config/routes.rb
Rails.application.routes.draw do
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index', as: :home

  resources :groups, :countries, :devices, :roles, :games, :users, :videos, :banners
  resources :faqs, except: :show
  resources :abouts, except: :show
  resources :find_teams, except: :show
  resources :find_users, except: :show
  resources :sponsors, only: %i[new create]
  resources :contacts, only: %i[new create]
  resources :group_invitations, only: %i[index show destroy]

  get 'administrator/index'
  post '/mensaje_global', to: 'administrator#mensaje_global', as: :mensaje_global
  # get '/sponsors', to: 'home#sponsors'
  get '/ggwp', to: 'home#ggwp'
  get '/terms_conditions', to: 'home#terms_conditions'
  put '/video/:id/vote', to: 'videos#vote', as: 'vote'
  put '/home/:id/firsttime', to: 'home#firsttimeuser', as: 'firsttimeuser'
  get 'contacts/new'
  get 'sponsors/new'
  get '/sponsors', to: 'sponsors#new'
  get '/list_equipos', to: 'home#list_user_equipos'
  get '/ggwp_all', to: 'home#ggwp_all'
  put '/group_invitations', to: 'group_invitations#new_invitation', as: 'new_invitation'

  resources :users do
    get :description
    get :avatar
    get :authorization
  end

  resources :groups do
    get :avatar
    get :new_member
    post :new_member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_videos
  before_action :top_videos
  layout 'application'

  def index
    @banners = Banner.where(active: true)
    @top4 = User.all.map {|user| [user.trophy, user.id]}.max(4)
    if user_signed_in?
      @user_own_group = Group.where(user_id: current_user.id)

      mail_count = current_user.mail_for_complete_profile_count.nil? ? 0 : current_user.mail_for_complete_profile_count
      is_profile_complete = current_user.attributes.map {|att| att.last == nil || att.last == ""}.count(true)
      last_mail_sent = current_user.mail_for_complete_profile
      if mail_count <=3 && is_profile_complete != 0
        if last_mail_sent.nil?
          send_mail(mail_count, current_user.id)
        else
          if last_mail_sent + 24*(2**mail_count).hours == Date.today
            send_mail(mail_count, current_user.id)
          end
        end
      end
    end
  end

  def sponsors
  end

  def list_user_equipos
    @breadcrumbs = 'Listado de Equipos'
    @breadcrumbs_subtitle = 'Equipos'
    @users = User.where(option: 'equipo')
    @users_pagination = @users.paginate(page: params[:page], per_page: 6).order(nickname: :asc)
  end

  def firsttimeuser
    @user = User.find_by(id: current_user.id)
    @user.update(firsttime: 0)
    redirect_to user_path(@user)
  end

  def ggwp
    @ggwp_active = 'active'
    @videos_pagination = @videos.paginate(page: params[:page], per_page: 6)
    def find_video(video)
      @video = Video.find_by id: video
      @user = User.find_by id: @video.user_id
    end
  end

  def ggwp_all
    @videos_pagination = @videos.paginate(page: params[:page], per_page: 24)
    def find_video(video)
      @video = Video.find_by id: video
      @user = User.find_by id: @video.user_id
    end
  end

  def terms_conditions
    @breadcrumbs = 'Legales'
    @breadcrumbs_subtitle = 'Términos y condiciones'
  end

  private
  def top_videos
    start_month = Date.today.last_month.beginning_of_month
    end_month = Date.today.last_month.end_of_month
    start_week = Date.today.last_week.beginning_of_week
    end_week = Date.today.last_week.end_of_week
    #@videos_week = Video.select { |video| video.id if video.created_at.year == Date.today.year && video.created_at.month == Date.today.month && video.created_at.to_date.cweek == Date.today.cweek && video.approved }
    @videos_week = Video.select { |video| video.id if video.created_at.to_date.between?(start_week, end_week) && video.approved }
    #@videos_month = Video.select { |video| video.id if video.created_at.year == Date.today.year && video.created_at.month == Date.today.month && video.approved}
    @videos_month = Video.select { |video| video.id if video.created_at.to_date.between?(start_month, end_month) && video.approved}
    @top3 = @videos_month.map {|video| [Vote.where(video_id: video).count, video]}.max(3)
    @top1 = @videos_month.map {|video| [Vote.where(video_id: video).count, video]}.max
    @top_week = @videos_week.map {|video| [Vote.where(video_id: video).count, video]}.max
    @videos_all = Video.all.map {|video| video.id}
    @top3_all = @videos_all.map {|video| [Vote.where(video_id: video).count, video]}.max(3)
  end

  def send_mail(mail_count, user_id)
    @sendmail = Contact.new(
      nombre: 'FreeAgents',
      email: 'info@freeagents.gg',
      nickname: '',
      mail_to: current_user.email,
      asunto: 'Completa tu perfil de Freeagents',
      mensaje: "Hola!, #{current_user.name}. Te enviamos este mensaje para recordarte que necesitamos que completes tu perfil de FreeAgents. Gracias!",
      opcion: 'completar perfil'
    )
    @sendmail.request = request
    @sendmail.deliver
    user = User.find_by(id: user_id)
    user.update(mail_for_complete_profile: Date.today, mail_for_complete_profile_count: mail_count + 1)
  end

  def set_videos
    @videos = Video.where(approved: true)
  end
end

app/views/home/ggwp.html.erb
<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-8">
      <div class="nk-gap-2"></div>
      <h3 class="nk-decorated-h-2">
            <span>
              <span class="text-main-1">Jugada Ganadora </span> de <%= l(Date.today.last_month, format: "%B") %></span>
      </h3>

      <!-- START: Now Playing -->
      <div class="responsive-embed responsive-embed-16x9">
        <% if @top1.present? %>
          <% if @top1.last.present? %>
            <%= Video.find_by(id: @top1.last.id).embeded.html_safe %>
          <% end %>
        <% end %>
      </div>
      <!-- END: Now Playing -->

      <!-- START: Match Description -->
      <div class="nk-gap-2"></div>
      <div class="row">
        <div class="col-4">
          <% if @top1.present? %>
            <% if find_video(@top1.last.id).image.present? %>
              <%= image_tag(find_video(@top1.last.id).image, width: '65%') %>
            <% else %>
              <%= image_tag('logo.png', width: '65%') %>
            <% end %>
          <% end %>
        </div>
        <div class="col-8">
          <div class="ggwp-index">
            <h3 class="h4">
              <% if !@top1.present? %>
                No hubo resultados de la votación
              <% else %>
                Video ganador de <i></i><%= find_video(@top1.last).nickname %></i>
              <% end %>
            </h3>
            <% if @top1.present? %>
              <%= image_tag('icons/ico_trofeo.png', width: '100') %>
              <h4 class="text-white"><%= @top1.first %></h4>
            <% end %>
          </div>
        </div>
      </div>
      <!-- END: Match Description -->

      <!-- START: Share -->
      <div class="nk-gap"></div>
      <div class="nk-post-share social-container">
        <span class="h5">Compartir:</span>

        <ul class="nk-social-links-2">
          <li>
              <a href="https://www.facebook.com/sharer.php?u=<%= request.base_url + '/ggwp' %>" class="nk-social-facebook facebook" title="Compartir en Facebook" data-share="facebook">
                <span class="fab fa-facebook"></span>
              </a>
          </li>
          <li>
                <a href="https://twitter.com/intent/tweet?url=<%= request.base_url + '/ggwp' %>" class="nk-social-twitter" title="Compartir en Twitter" data-share="twitter">
                  <span class="fab fa-twitter"></span>
                </a>
          </li>

          <!-- Additional Share Buttons
                    <li><span class="nk-social-linkedin" title="Share page on LinkedIn" data-share="linkedin"><span class="fa fa-linkedin"></span></span></li>
                    <li><span class="nk-social-vk" title="Share page on VK" data-share="vk"><span class="fa fa-vk"></span></span></li>
                -->
        </ul>
      </div>
      <!-- END: Share -->

      <!-- START: Latest Matches -->

      <div class="nk-gap-2"></div>
      <h3 class="nk-decorated-h-2">
        <span class="text-main-1">Votá</span> tu favorito</span>
      </h3>
      <% cache @videos_pagination do %>
        <% @videos_pagination.each do |video| %>
          <% cache video do %>
            <div class="nk-gap"></div>
            <div class="responsive-embed responsive-embed-16x9">
              <%= video.embeded.html_safe %>
              <% if user_signed_in? && current_user.role.id == 2 %>
                <div class="delete-video-button">
                  <%= link_to video_path(id: video, ggwp: true), method: :delete, data: { confirm: 'Está seguro?' }, class: "nk-btn nk-btn-rounded nk-btn-color-white nk-anchor text-white" do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="nk-gap"></div>
            <div class="row">
              <div class="col-4">
                <% @user =  User.find_by(id: video.user_id) %>
                <% if @user.image.present? %>
                  <%= image_tag(@user.image, width: '65%') %>
                <% else %>
                  <%= image_tag('logo.png', width: '65%') %>
                <% end %>
              </div>
              <div class="col-8">
                <div class="ggwp-vote" id="video-<%= video.id %>">
                  <div class="row">
                    <div class="col-12">
                      <h3 class="h4">Video de <i><%= @user.nickname %></i></h3>
                    </div>
                    <div class="col-4">
                      <%= image_tag('icons/ico_trofeo.png', width: '80') %>
                    </div>
                    <div class="col-8">
                      <h4 class="text-white trofeos_acumulados">
                        trofeos acumulados <br>
                        <strong><%= Vote.where(video_id: video.id).count %></strong>
                      </h4>
                    </div>
                    <% if user_signed_in? %>
                      <div class="col-12 boton-votacion">
                        <% if !video.voted?(current_user) %>
                          <%= button_to "Votar", vote_path(video), method: 'put', class: 'nk-btn nk-btn-rounded nk-btn-color-main-1 .nk-btn-color-dark-3', onclick: "vote(#{video.id});"  %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <!-- END: Match Description -->
      <div class="nk-gap-2"></div>
      <!-- START: Pagination -->
      <div class="col-lg-12">
        <div class="nk-pagination text-center">
          <nav>
            <%= will_paginate(
                  @videos_pagination,
                  previous_label: '<span class="ion-ios-arrow-back"></span>',
                  next_label: '<span class="ion-ios-arrow-forward"></span>',
                  inner_window: 1, outer_window: 1
                  )
            %>
          </nav>
        </div>
      </div>
      <!-- END: Pagination -->


    </div>
    <div class="col-lg-4">
      <!--
            START: Sidebar

            Additional Classes:
                .nk-sidebar-left
                .nk-sidebar-right
                .nk-sidebar-sticky
        -->
      <aside class="nk-sidebar nk-sidebar-right nk-sidebar-sticky">
        <div class="nk-widget nk-widget-highlighted">
          <h4 class="nk-widget-title">
            <span><span class="text-main-1">Top 3</span> GGWP de <%= l(Date.today.last_month, format: "%B") %></span>
          </h4>
          <div class="nk-widget-content">
            <% @top3.each do |video| %>
              <div class="nk-gallery-item-box">
              <% if !video.last.nil? %>
                <%= Video.find_by(id: video.last).embeded.html_safe %>
                  <% if user_signed_in? && current_user.role.id == 2 %>
                    <div class="delete-video-button">
                      <%= link_to video_path(id: video, ggwp: true), method: :delete, data: { confirm: 'Está seguro?' }, class: "nk-btn nk-btn-rounded nk-btn-color-white nk-anchor text-white" do %>
                        <i class="fas fa-trash"></i>
                      <% end %>
                    </div>
                  <% end %>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="nk-widget nk-widget-highlighted">
          <h4 class="nk-widget-title">
                <span>
                  <span class="text-main-1">Mas</span> ggwp</span>
          </h4>
          <div class="nk-widget-content">
            <div class="nk-popup-gallery">
              <div class="row sm-gap vertical-gap">
                <% (1..3).each do %>
                  <div class="col-12">
                    <% video = Video.ids.sort.sample %>
                    <div class="nk-gallery-item-box">
                      <%= Video.find_by(id: video).embeded.html_safe %>
                      <% if user_signed_in? && current_user.role.id == 2 %>
                        <div class="delete-video-button">
                          <%= link_to video_path(id: video, ggwp: true), method: :delete, data: { confirm: 'Está seguro?' }, class: "nk-btn nk-btn-rounded nk-btn-color-white nk-anchor text-white" do %>
                            <i class="fas fa-trash"></i>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="col-12">
                <div class="nk-product-cat">
                  <div class="nk-product-cont text-center">
                    <div class="nk-gap-1"></div>
                    <%= link_to 'Ver más', ggwp_all_path, class: 'nk-btn nk-btn-rounded nk-btn-color-dark-3 nk-btn-hover-color-main-1' %>
                  </div>
                </div>
              </div>
              <div class="nk-gap-2"></div>
            </div>
          </div>
        </div>

      </aside>
      <!-- END: Sidebar -->
    </div>
  </div>
</div>

<div class="nk-gap-2"></div>

<script>
    /*$(function () {
        $(".social-container a, .social-container button").jqss();
    });*/
    function vote(video_id){
        console.log(video_id)
        valor_actual = $("#video-"+video_id+" .trofeos_acumulados strong").html();
        $("#video-"+video_id+" .button_to").addClass('d-none');
        $("#video-"+video_id+" .trofeos_acumulados strong").html((parseInt(valor_actual) + 1).toString());
    }
</script>

app/views/home/index.html.erb
<div class="nk-gap-2"></div>
<%# reset_counter = current_user.update(mail_for_complete_profile: nil, mail_for_complete_profile_count: nil) %>
<%# console %>
<div class="container">

  <!-- START: Image Slider -->
  <div class="nk-image-slider" data-autoplay="8000">
    <% cache @banners do %>
      <% @banners.each do |banner| %>
        <% cache banner do %>
          <div class="nk-image-slider-item">
            <% if banner.image.present? && banner.thumb.blob.present? %>
              <img src="<%= rails_blob_path(banner.image) %>" class="nk-image-slider-img" data-thumb="<%= rails_blob_path(banner.thumb) %>">
              <%#= image_tag(banner.image, class: 'nk-image-slider-img', data: { thumb: image_path(banner.thumb.blob.filename).html_safe }) %>
            <% end %>
            <%#= image_path(banner.image, class: 'nk-image-slider-img', data: {thumb: image_path(banner.thumb)}) %>
            <% if banner.title.present? %>
              <div class="nk-image-slider-content">

                <h3 class="h4"><%= banner.title %></h3>
                <% if banner.content.present? %>
                  <p class="text-white"><%= banner.content %></p>
                <% end %>

              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <!-- END: Image Slider -->

  <!-- START: Categories -->
  <div class="nk-gap-2"></div>
  <div class="row vertical-gap">
    <div class="col-lg-3">
      <div class="nk-feature-1">
        <!--<div class="nk-feature-icon">
          <%#= image_tag('icons/ico_mouse.png') %>
        </div>-->
        <div class="nk-feature-cont text-center">
          <% if user_signed_in? %>
            <h3 class="nk-feature-title"><%= link_to "crea tu perfil", user_path(current_user) %></h3>
          <% end %>
          <% unless user_signed_in? %>
            <h4 class="nk-feature-title text-main-1">
              <%= link_to "registrate", new_user_registration_path, class: 'pb-2' %>
              <br>
            </h4>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="nk-feature-1">
        <!--<div class="nk-feature-icon">
          <%#= image_tag('icons/ico_ps4.png') %>
        </div>-->
        <div class="nk-feature-cont text-center">
          <% if user_signed_in? %>
            <% if current_user.option == 'jugador' %>
              <h4 class="nk-feature-title text-main-1"><%= link_to 'Unite a un equipo', find_users_path %></h4>
            <% else %>
              <h3 class="nk-feature-title"><%= link_to 'Creá tu equipo', new_group_path(user: current_user.id) %></h3>
              <% if @user_own_group %>
                <h3 class="nk-feature-title"><%= link_to 'Ver tus equipos', groups_path(user: current_user.id) %></h3>
              <% end %>
            <% end %>
          <% else %>
            <h3 class="nk-feature-title"><%= link_to "Equipos", groups_path %></h3>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="nk-feature-1">
        <!--<div class="nk-feature-icon">
          <%#= image_tag('icons/ico_xbox.png') %>
        </div>-->
        <div class="nk-feature-cont text-center">
          <h3 class="nk-feature-title"><%= link_to 'Tu jugada favorita', ggwp_path %></h3>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="nk-feature-1">
        <!--<div class="nk-feature-icon">
          <%#= image_tag('icons/ico_xbox.png') %>
        </div>-->
        <div class="nk-feature-cont text-center">
          <form action="https://www.paypal.com/donate" method="post" target="_top">
            <input type="hidden" name="hosted_button_id" value="VE5KUV38QN6U4" />
            <button type="submit" class='boton-donar'><h3 class="nk-feature-title">Cómo apoyarnos?</h3></button>
            <!--<input type="image" src="https://pics.paypal.com/00/s/YjQ3N2E2ODEtMzZhNy00NDZhLThjMDEtZWNjMDQ5YjE5ODI4/file.PNG" border="0" name="submit" title="Cómo apoyar a Free Agents Esports" alt="Donar con PayPal" />-->
            <img alt="" border="0" src="https://www.paypal.com/en_AR/i/scr/pixel.gif" width="1" height="1" />
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- END: Categories -->

  <div class="nk-gap-2"></div>
  <div class="row vertical-gap">
    <div class="col-lg-8">

      <!-- START: Latest Matches -->
      <div class="nk-gap-2"></div>
      <h3 class="nk-decorated-h-2">
            <span>
              <span class="text-main-1">Video </span> de la semana
            </span>
      </h3>
      <div class="nk-gap"></div>
      <div class="row">
        <% if !@top_week.present? %>
          No hubo resultados de votación
        <% else %>
          <div class="col-md-4">
            <div class="nk-widget-match p-0">
              <div class="nk-widget-match-teams">
                <div class="nk-widget-match-team-logo">
                  <% if @top_week.present? %>
                    <% if find_video(@top_week.last.id).image.present? %>
                      <%= image_tag(find_video(@top_week.last.id).image, width: '65%') %>
                    <% else %>
                      <%= image_tag('logo.png', width: '65%') %>
                    <% end %>
                  <% end %>
                </div>
                <div class="nk-match-score bg-dark-3 text-center">
                  <% if @top_week.present? %>
                    <% @user1 = User.find_by(id: @top_week.last.user_id) %>
                    <%= @user1.nickname %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="nk-gap-2"></div>
            <div class="ggwp-index">
              <% if @top_week.present? %>
                <%= image_tag('icons/ico_trofeo.png', width: '80') %>
                <h4 class="text-white"><%= @top_week.first %></h4>
                <%= link_to 'Ver Perfil', user_path(@user1), class: 'nk-btn nk-btn-rounded nk-btn-color-main-1 .nk-btn-color-dark-3' %>
              <% end %>
            </div>

          </div>
          <div class="col-md-8">
            <div class="responsive-embed responsive-embed-16x9">
              <% if @top_week.present? %>
                <% if @top_week.last.present? %>
                  <%= Video.find_by(id: @top_week.last.id).embeded.html_safe %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <!-- END: Latest Matches -->

      <div class="nk-gap-2"></div>
      <h3 class="nk-decorated-h-2">
            <span>
              <span class="text-main-1">Video </span> del mes
            </span>
      </h3>
      <div class="nk-gap"></div>
      <div class="row">
        <% if @top1.present? %>
          <div class="col-md-4">
            <div class="nk-widget-match p-0">
              <div class="nk-widget-match-teams">
                <div class="nk-widget-match-team-logo">
                  <% if @top1.last.present? %>
                    <% if find_video(@top1.last.id).image.present? %>
                      <%= image_tag(find_video(@top1.last.id).image, width: '65%') %>
                    <% else %>
                      <%= image_tag('logo.png', width: '65%') %>
                    <% end %>
                  <% end %>
                  <div class="nk-match-score bg-dark-3 text-center">
                    <% if @top1.present? %>
                      <% @user2 = User.find_by(id: @top1.last.user_id) %>
                      <%= @user2.nickname %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="ggwp-index">
                <% if @top1.present? %>
                  <%= image_tag('icons/ico_trofeo.png', width: '80') %>
                  <h4 class="text-white"><%= @top1.first %></h4>
                  <%= link_to 'Ver Perfil', user_path(@user2), class: 'nk-btn nk-btn-rounded nk-btn-color-main-1 .nk-btn-color-dark-3' %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="responsive-embed responsive-embed-16x9">
              <% if @top1.present? %>
                <% if @top1.last.present? %>
                  <%= Video.find_by(id: @top1.last.id).embeded.html_safe %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% else %>
          No hubo resultados de la votación
        <% end %>
      </div>

      <!-- START: Best Selling -->
      <div class="nk-gap-3"></div>
      <h3 class="nk-decorated-h-2">
            <span>
              <span class="text-main-1">Jugadores</span> Destacados</span>
      </h3>
      <div class="nk-gap"></div>
      <div class="row vertical-gap">

        <% @top4.each do |top| %>
          <div class="col-md-6 mt-50 mb-30">
            <div class="nk-product-cat">
              <div class="row">
                <div class="col-sm-4 user-avatar">
                  <a class="nk-product-image">
                    <% if (User.find(top.last)).image.attached? %>
                      <%= image_tag((User.find(top.last)).image, width: '65%') %>
                    <% else %>
                      <%= image_tag('logo.png', width: '65%') %>
                    <% end %>
                  </a>
                </div>
                <div class="col-sm-8">
                  <div class="nk-product-cont">
                    <h3 class="nk-product-title h5"><%= truncate((User.find(top.last)).nickname, length:15) %></a>
                    </h3>
                    <!--<div class="nk-gap-1"></div>-->
                    <div class="nk-product-rating" data-rating="3">
                      <%#= image_tag('icons/ico_trofeo.png', width: '45%') %>
                      <%= image_tag('icons/ico_corona.png', width: '40px') %>
                      <small class="text-white"><%= top.first %></small>
                    </div>
                    <!--<div class="nk-gap-1"></div>
                    <div class="nk-gap-1"></div>-->
                    <div>
                      <%= link_to 'Ver perfil', user_path(top.last), class: 'nk-btn nk-btn-rounded nk-btn-color-dark-3 nk-btn-hover-color-main-1' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="col-12">
          <div class="nk-product-cat last">
            <div class="nk-product-cont text-center">
              <div class="nk-gap-1"></div>
              <%= link_to 'Ver más', games_path, class: 'nk-btn nk-btn-rounded nk-btn-color-dark-3 nk-btn-hover-color-main-1' %>
            </div>
          </div>
        </div>

      </div>
      <!-- END: Best Selling -->


      <div class="nk-gap-2"></div>


    </div>
    <div class="col-lg-4">
      <!--
            START: Sidebar

            Additional Classes:
                .nk-sidebar-left
                .nk-sidebar-right
                .nk-sidebar-sticky
        -->
      <aside class="nk-sidebar nk-sidebar-right nk-sidebar-sticky">

        <!--<div class="nk-widget nk-widget-highlighted">
          <h4 class="nk-widget-title">
                <span>
                  <span class="text-main-1">Video</span> del mes</span>
          </h4>
          <div class="nk-widget-content">
            <div class="nk-gallery-item-box mb-15">
              <%# if @top1.present? %>
                <%# if @top1.last.present? %>
                  <%#= Video.find_by(id: @top1.last.id).embeded.html_safe %>
                <%# end %>
              <%# else %>
                No hubo resultados de la votación
              <%# end %>
            </div>
          </div>
        </div>-->

        <div class="nk-widget nk-widget-highlighted">
          <h4 class="nk-widget-title">
                <span>
                  <span class="text-main-1">Top 3</span> Videos Más votados</span>
          </h4>
          <div class="nk-widget-content">
            <% cache @top3_all do %>
              <% @top3_all.each do |video| %>
                <% cache video do %>
                  <div class="nk-gallery-item-box mb-15">
                    <% if !video.last.nil? %>
                      <%= Video.find_by(id: video.last).embeded.html_safe %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="col-12">
            <div class="nk-product-cat last">
              <div class="nk-product-cont text-center">
                <div class="nk-gap-1"></div>
                <%= link_to 'Ver más', ggwp_path, class: 'nk-btn nk-btn-rounded nk-btn-color-dark-3 nk-btn-hover-color-main-1' %>
              </div>
            </div>
          </div>
          <div class="nk-gap-2"></div>
        </div>

      </aside>
      <div class="nk-gap-2"></div>
      <!-- END: Sidebar -->
    </div>
  </div>
</div>

<!-- Seiyria Bootstrap Slider -->
<script src="<%= request.base_url + '/bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.js' %>"></script>

app/views/home/list_user_equipos.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <!-- START: Teams -->
      <% @users_pagination.each do |user| %>
        <div class="nk-team">
          <div class="nk-team-logo">
            <% if user.image.attached? %>
              <%= image_tag(user.image, width: '126px') %>
            <% else %>
              <%= image_tag('logo.png', width: '126px') %>
            <% end %>
          </div>
          <div class="nk-team-cont">
            <div class="nk-content">
              <h3 class="h5 mb-20">
                <span class="text-main-1"><%= link_to user.nickname, user %></span>
              </h3>
              <p class="h5 mb-20 ml-30">
                <% if user_signed_in? && current_user.role.id == 2 %>
                  <%= link_to edit_user_path(user) do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-trash ml-10"></i>
                  <% end %>
                <% end %>
              </p>
            </div>
            <i class="fa fa-file-video-o"></i> <%= Video.where(user_id: user.id).count %> Videos compartidos
            <!--<div class="nk-team-photo" style="background-image: url(<%#= image_path('team-photo.png') %>);"></div>-->
          </div>
        </div>
      <% end %>
      <!-- END: Teams -->
      <div class="nk-gap-2"></div>
      <!-- START: Pagination -->
      <div class="col-lg-9">
        <div class="nk-pagination nk-pagination-left">
          <nav>
            <%= will_paginate(
                  @users_pagination,
                  previous_label: '<span class="ion-ios-arrow-back"></span>',
                  next_label: '<span class="ion-ios-arrow-forward"></span>',
                  )
            %>
          </nav>
        </div>
      </div>
      <!-- END: Pagination -->

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>
<div class="nk-gap-2"></div>