config/routes.rb
Rails.application.routes.draw do
  resources :partners
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index', as: :home

  resources :groups, :countries, :devices, :roles, :games, :users, :videos, :banners
  resources :faqs, except: :show
  resources :abouts, except: :show
  resources :find_teams, except: :show
  resources :find_users, except: :show
  resources :sponsors, only: %i[new create]
  resources :contacts, only: %i[new create]
  resources :group_invitations, only: %i[index show destroy]

  get 'administrator/index'
  post '/mensaje_global', to: 'administrator#mensaje_global', as: :mensaje_global
  # get '/sponsors', to: 'home#sponsors'
  get '/ggwp', to: 'home#ggwp'
  get '/terms_conditions', to: 'home#terms_conditions'
  put '/video/:id/vote', to: 'videos#vote', as: 'vote'
  put '/home/:id/firsttime', to: 'home#firsttimeuser', as: 'firsttimeuser'
  get 'contacts/new'
  get 'sponsors/new'
  get '/sponsors', to: 'sponsors#new'
  get '/list_equipos', to: 'home#list_user_equipos'
  get '/ggwp_all', to: 'home#ggwp_all'
  put '/group_invitations', to: 'group_invitations#new_invitation', as: 'new_invitation'

  resources :users do
    get :description
    get :avatar
    get :authorization
  end

  resources :groups do
    get :avatar
    get :new_member
    post :new_member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/find_user.rb
class FindUser < ApplicationRecord
end

app/controllers/find_users_controller.rb
class FindUsersController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_find_user, only: [:show, :edit, :update, :destroy]
  before_action :check_group, only: [:new, :create]
  before_action :set_breadcrumb
  before_action :set_options_for_select, only: [:new, :update, :show]
  layout('application')

  # GET /find_users
  def index
    @breadcrumbs_subtitle = 'Listado de Búsqueda'
    @country_options = Country.all.map {|country| [country.name, country.id]}
    @game_options = Game.all.map { |game| [game.name, game.id] }.sort
    @tipo_equipo = [['Teams', 'amateur'],['Teams Pro', 'pro']]

    if params[:nombre].nil?
      find_users = FindUser.all

      if params[:filter].present?
        find_users_all = FindUser.all
        params_select = params.select {|k,v| [k.to_sym,v] if v.present? && k != 'controller' && k != 'filter' && k != 'action' && k != 'commit'}
        search_params = params_select.to_enum.each {|param| ["#{param.first} LIKE ?", param.last]}

        find_users = find_users_all.where(search_params.permit(:nombre, :winrate, :partidas_jugadas, :rango_horario, :pais, :juego, :rol, :posicion, :tipo))
      end
    else
      find_groups = Group.where(Group.arel_table[:name].matches('%'+params[:nombre]+'%'))
      find_users = FindUser.where(group_id: find_groups.ids)
    end

    @find_users_pagination = find_users.paginate(page: params[:page], per_page: 6).order(created_at: :asc)
  end

  # GET /find_users/1
  def show
  end

  # GET /find_users/new
  def new
    @find_user = FindUser.new
    @breadcrumbs_subtitle = 'Nueva Búsqueda'
  end

  # GET /find_users/1/edit
  def edit
    @breadcrumbs_subtitle = 'Modificar Búsqueda'
    @games = Game.all.map { |game| [game.name, game.id] }.sort
    @countries = Country.all.map {|country| [country.name, country.id]}
  end

  # POST /find_users
  def create
    @find_user = FindUser.new(find_user_params)
    @find_user.user_id = current_user.id
    @find_user.group_id = Group.find_by(user_id: current_user.id).id
    @find_user.tipo = current_user.tipo

    if @find_user.save
      redirect_to find_users_path, notice: 'Búsqueda de jugador creada.'
    else
      render :new
    end
  end

  # PATCH/PUT /find_users/1
  def update
    @find_user.tipo = User.find_by(id: @find_user.user_id).tipo
    if @find_user.update(find_user_params)
      redirect_to find_users_path, notice: 'Búsqueda de jugador actualizada.'
    else
      render :edit
    end
  end

  # DELETE /find_users/1
  def destroy
    @find_user.destroy
    redirect_to find_users_url, notice: 'Búsqueda de jugador eliminada.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_find_user
      @find_user = FindUser.find(params[:id])
    end

    def set_options_for_select
      @games = Game.all.map { |game| [game.name, game.id] }
      @countries = Country.all.map { |country| [country.name, country.id] }
    end

    def set_breadcrumb
      @breadcrumbs = 'Equipos buscando jugadores'
      @find_active = 'active'
    end

    def check_group
      redirect_to user_path(current_user.id), notice: 'No tienes un equipo creado' unless Group.find_by(user_id: current_user.id).present?
    end

    # Only allow a list of trusted parameters through.
    def find_user_params
      params.require(:find_user).permit(:user_id, :group_id, :title, :description, :rango_horario, :winrate, :rol, :partidas_jugadas, :posicion, :pais, :juego, :tipo)
    end
end

app/helpers/find_users_helper.rb
module FindUsersHelper
end

app/views/find_users/_form.html.erb
<%= form_with(model: find_user) do |form| %>
  <% if find_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(find_user.errors.count, "error") %> prohibited this find_user from being saved:</h2>

      <ul>
        <% find_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row vertical-gap">
    <div class="offset-lg-3 col-lg-6">
      <div class="row vertical-gap">
        <div class="col-md-6 text-center">
          <%= form.label 'Juego' %>
          <%= form.select :juego, options_for_select(@games, @find_user.juego),{blank: false}, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'Posición' %>
          <%= form.text_field :posicion, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'Partidas jugadas' %>
          <%= form.text_field :partidas_jugadas, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'Rol' %>
          <%= form.text_field :rol, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'Winrate' %>
          <%= form.text_field :winrate, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'Rango horario' %>
          <%= form.text_field :rango_horario, class: 'form-control required' %>
        </div>
        <div class="col-md-6 text-center">
          <%= form.label 'País' %>
          <%= form.select :pais, options_for_select(@countries,  @find_user.pais), {blank:false}, class: 'form-control required' %>
        </div>
      </div>
    </div>
    <div class="col-12">
      <div class="text-center">
        <div class="nk-gap-1"></div>
        <%= form.submit 'Confirmar', class: 'nk-btn nk-btn-rounded nk-btn-color-white' do %>
          <span class="icon"><i class="ion-paper-airplane"></i></span>
        <% end %>
        <div class="nk-gap-1"></div>
      </div>
    </div>
  </div>

<% end %>

app/views/find_users/edit.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <%= render 'form', find_user: @find_user %>

      <div class="text-center">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/find_users/index.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">
      <% if user_signed_in? %>
        <div class="row filtros">
          <div class="col-md-6">
            <%= form_with(controller: controller, method: 'get', class: 'd-flex') do |f| %>
              <%= f.text_field :nombre, class: 'form-control', placeholder: 'Buscar equipo', data: { turbolinks: false } %>
              <%= button_tag type: 'submit', class: 'nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3 ml-15' do %>
                <i class="fas fa-search"></i>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-6 boton-filtro">
            <%= link_to 'Limpiar filtros', find_users_path, class:"nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3 mr-5" %>
            <button class="nk-btn nk-btn-rounded nk-btn-color-main-2 .nk-btn-color-dark-3" data-toggle="modal" data-target="#modalFiltrarBusqueda">Filtrar Equipos</button>
          </div>
        </div>
      <% end %>

      <div class="row">
        <!-- START: Teams -->
        <% @find_users_pagination.each do |find_user| %>
          <%
            user = User.find_by(id: find_user.user_id)
            group = Group.find_by(id: find_user.group_id)
            game = Game.find_by(id: find_user.juego)
            country = Country.find_by(id: find_user.pais)
          %>
          <div class="col-lg-6 my-2">
            <div class="nk-team">
              <div class="row">
                <div class="col-md-4 d-flex justify-content-center align-items-center">
                  <div class="photo-logo">
                    <% if group.image.present? %>
                      <%= image_tag(group.image, width: '100%') %>
                    <% else %>
                      <%= image_tag('logo.png', width: '100%') %>
                    <% end %>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="nk-team-cont">
                    <div class="nk-content flex-column">
                      <h3 class="mb-0"><%= link_to group.name, group_path(group).truncate(12) %></h3>
                      <h3 class="h5 mb-20">
                        <span class="text-main-1">BUSCO JUGADOR</span>
                      </h3>
                    </div>
                    <p class="mb-20">
                      Juego: <%= game.name unless game.nil? %></span> <br>
                      Partidas jugadas: <%= find_user.partidas_jugadas %> <br>
                      Rol: <%= find_user.rol %> <br>
                      Posición: <%= find_user.posicion %> <br>
                      Winrate: <%= find_user.winrate %> <br>
                      País: <%= country.name unless country.nil? %> <br>
                      Rango horario: <%= find_user.rango_horario %>
                    </p>

                    <% if user_signed_in? && current_user.active? && current_user.option == 'jugador' %>
                      <div class="boton_contacto">
                        <%= link_to 'Apuntarme al equipo', contacts_new_path(usuario: user.email, grupo: group.name), class:'nk-btn nk-btn-rounded nk-btn-color-black' %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="options-icons">
                  <% if user_signed_in? && ( current_user.role.id == 2 || current_user.id == find_user.user_id )  %>
                    <%= link_to edit_find_user_path(find_user) do %>
                      <i class="fa fa-edit"></i>
                    <% end %>
                    <%= link_to find_user, method: :delete, data: { confirm: '¿Estás seguro?' } do %>
                      <i class="fa fa-trash ml-10"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <!-- END: Teams -->
      </div>
      <div class="nk-gap-2"></div>
      <!-- START: Pagination -->
      <div class="col-lg-12">
        <div class="nk-pagination text-center">
          <nav>
            <%= will_paginate(
                  @find_users_pagination,
                  previous_label: '<span class="ion-ios-arrow-back"></span>',
                  next_label: '<span class="ion-ios-arrow-forward"></span>',
                  inner_window: 1, outer_window: 1
                  )
            %>
          </nav>
        </div>
      </div>
      <!-- END: Pagination -->

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>
<div class="nk-gap-2"></div>

app/views/find_users/new.html.erb
<%= render '_partials/breadcrumbs' %>

<div class="container">
  <div class="row vertical-gap">
    <div class="col-lg-12">

      <%= render 'form', find_user: @find_user %>

      <div class="text-center">
        <%= link_to 'Volver', user_path(current_user.id) %>
      </div>

    </div>

  </div>
</div>

<div class="nk-gap-2"></div>

app/views/find_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @find_user.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @find_user.group_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @find_user.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @find_user.description %>
</p>

<%= link_to 'Edit', edit_find_user_path(@find_user) %> |
<%= link_to 'Back', find_users_path %>